{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lenebf.plugin",
    "module": "hello",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "6u73yr5wbzcg5ajm25fdecheka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hello-0.0.1.jar",
          "url": "hello-0.0.1.jar",
          "size": 5292,
          "sha512": "a358bc05f73de49b89de1e8334f38428c5f0004ec7cd4807ba3f8e9db55759bb0ca8310858a9e0012a1cf5f5ee1ddab8f89b7d15692b0dd7c6df381c3a5ca23d",
          "sha256": "d13d5c2fb8740a0c858bd1684b131b735ff37a84cdaddab2213a6508ee56c553",
          "sha1": "532b69362dfcedcd7555160ebafd0671d2fc50a7",
          "md5": "3fbbc86fbacf424b899857e628b836f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hello-0.0.1.jar",
          "url": "hello-0.0.1.jar",
          "size": 5292,
          "sha512": "a358bc05f73de49b89de1e8334f38428c5f0004ec7cd4807ba3f8e9db55759bb0ca8310858a9e0012a1cf5f5ee1ddab8f89b7d15692b0dd7c6df381c3a5ca23d",
          "sha256": "d13d5c2fb8740a0c858bd1684b131b735ff37a84cdaddab2213a6508ee56c553",
          "sha1": "532b69362dfcedcd7555160ebafd0671d2fc50a7",
          "md5": "3fbbc86fbacf424b899857e628b836f8"
        }
      ]
    }
  ]
}
